package dao.com.co.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY.
 */
public class Category {

    private Long id;
    /** Not-null value. */
    private String category_id;
    /** Not-null value. */
    private String nameCategory;
    /** Not-null value. */
    private String urlImage;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String category_id, String nameCategory, String urlImage) {
        this.id = id;
        this.category_id = category_id;
        this.nameCategory = nameCategory;
        this.urlImage = urlImage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCategory_id() {
        return category_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategory_id(String category_id) {
        this.category_id = category_id;
    }

    /** Not-null value. */
    public String getNameCategory() {
        return nameCategory;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNameCategory(String nameCategory) {
        this.nameCategory = nameCategory;
    }

    /** Not-null value. */
    public String getUrlImage() {
        return urlImage;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrlImage(String urlImage) {
        this.urlImage = urlImage;
    }

}
