package dao.com.co.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import dao.com.co.greendao.Category;
import dao.com.co.greendao.SubCategory;
import dao.com.co.greendao.Details;

import dao.com.co.greendao.CategoryDao;
import dao.com.co.greendao.SubCategoryDao;
import dao.com.co.greendao.DetailsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig subCategoryDaoConfig;
    private final DaoConfig detailsDaoConfig;

    private final CategoryDao categoryDao;
    private final SubCategoryDao subCategoryDao;
    private final DetailsDao detailsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        subCategoryDaoConfig = daoConfigMap.get(SubCategoryDao.class).clone();
        subCategoryDaoConfig.initIdentityScope(type);

        detailsDaoConfig = daoConfigMap.get(DetailsDao.class).clone();
        detailsDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        subCategoryDao = new SubCategoryDao(subCategoryDaoConfig, this);
        detailsDao = new DetailsDao(detailsDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(SubCategory.class, subCategoryDao);
        registerDao(Details.class, detailsDao);
    }
    
    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        subCategoryDaoConfig.getIdentityScope().clear();
        detailsDaoConfig.getIdentityScope().clear();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public SubCategoryDao getSubCategoryDao() {
        return subCategoryDao;
    }

    public DetailsDao getDetailsDao() {
        return detailsDao;
    }

}
