package dao.com.co.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DETAILS.
 */
public class Details {

    private Long id;
    /** Not-null value. */
    private String id_details;
    /** Not-null value. */
    private String item_subcategory_id;
    /** Not-null value. */
    private String name_details;
    /** Not-null value. */
    private String description;
    /** Not-null value. */
    private String urlImage_items;
    /** Not-null value. */
    private String urlImage_left;
    /** Not-null value. */
    private String urlImage_right;

    public Details() {
    }

    public Details(Long id) {
        this.id = id;
    }

    public Details(Long id, String id_details, String item_subcategory_id, String name_details, String description, String urlImage_items, String urlImage_left, String urlImage_right) {
        this.id = id;
        this.id_details = id_details;
        this.item_subcategory_id = item_subcategory_id;
        this.name_details = name_details;
        this.description = description;
        this.urlImage_items = urlImage_items;
        this.urlImage_left = urlImage_left;
        this.urlImage_right = urlImage_right;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getId_details() {
        return id_details;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId_details(String id_details) {
        this.id_details = id_details;
    }

    /** Not-null value. */
    public String getItem_subcategory_id() {
        return item_subcategory_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setItem_subcategory_id(String item_subcategory_id) {
        this.item_subcategory_id = item_subcategory_id;
    }

    /** Not-null value. */
    public String getName_details() {
        return name_details;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName_details(String name_details) {
        this.name_details = name_details;
    }

    /** Not-null value. */
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(String description) {
        this.description = description;
    }

    /** Not-null value. */
    public String getUrlImage_items() {
        return urlImage_items;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrlImage_items(String urlImage_items) {
        this.urlImage_items = urlImage_items;
    }

    /** Not-null value. */
    public String getUrlImage_left() {
        return urlImage_left;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrlImage_left(String urlImage_left) {
        this.urlImage_left = urlImage_left;
    }

    /** Not-null value. */
    public String getUrlImage_right() {
        return urlImage_right;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrlImage_right(String urlImage_right) {
        this.urlImage_right = urlImage_right;
    }

}
