package dao.com.co.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUB_CATEGORY.
 */
public class SubCategory {

    private Long id;
    /** Not-null value. */
    private String subCategory_id;
    /** Not-null value. */
    private String subCategory;

    public SubCategory() {
    }

    public SubCategory(Long id) {
        this.id = id;
    }

    public SubCategory(Long id, String subCategory_id, String subCategory) {
        this.id = id;
        this.subCategory_id = subCategory_id;
        this.subCategory = subCategory;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSubCategory_id() {
        return subCategory_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSubCategory_id(String subCategory_id) {
        this.subCategory_id = subCategory_id;
    }

    /** Not-null value. */
    public String getSubCategory() {
        return subCategory;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSubCategory(String subCategory) {
        this.subCategory = subCategory;
    }

}
